openapi: 3.0.0
info:
  title: Authentication API
  version: 1.0.0
paths:
  /auth/signin:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: string
                  example: testuser@hotmail.com
                password:
                  type: string
                  format: string
                  example: 123
              required:
                - email
                - password
      description: Auth handler to login / logout users
      responses:
        '200':
          description: Returns a user and a token string.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
                properties:
                  token: string
  /auth/signout:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  format: integer
                  example: 1

              required:
                - id
      description: Auth handler to log out user
      responses:
        '200':
          description: Returns a boolean.
  /auth/signup:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties: 
                 name:
                  type: string
                 email:
                  type: string
                 age:
                  type: integer
                 address:
                  type: string
                 password: 
                  type: string
                  required: 
                    - name
                    - email
                    - age
                    - address
                    - password
            
      description: Auth handler to register user
      responses:
        '200':
          description: Returns a user with hash instead of plain text password.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserWithHash'
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        age:
          type: integer
        address:
          type: string
    UserWithHash:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        age:
          type: integer
        address:
          type: string
        hash:
          type: string
