version: '3.8'

services:
  # PostgreSQL Service
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: itrocadata
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Node.js Service
  nodejs:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://admin:123@postgres:5432/itrocadata

volumes:
  postgres_data:
