openapi: 3.0.0
info:
  title: User API
  version: 1.0.0
paths:
  /user:
    get:
      security:
        - bearerAuth: []
      description: User handler to get a user by token
      responses:
        '200':
          description: Returns a User.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
components:
  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT # optional, arbitrary value for documentation purposes
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        age:
          type: integer
        address:
          type: string
