openapi: 3.0.0
info:
  title: User API
  version: 1.0.0
paths:
  /user:
    post:
      description: User handler to create random users
      responses:
        '200':
          description: Returns a User.
  /user/{id}:
    get:
      description: User handler to get a user by ID
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the user to retrieve
          schema:
            type: integer
      responses:
        '200':
          description: Returns a User.
