openapi: 3.0.0
info:
  title: User API
  version: 1.0.0
paths:
  /user:
    post:
      description: User handler to create random users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'

      responses:
        '200':
          description: Returns a User.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /user/{id}:
    get:
      description: User handler to get a user by ID
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the user to retrieve
          schema:
            type: integer
      responses:
        '200':
          description: Returns a User.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          required:
            - 'false'
        email:
          type: string
      example:
        id: 1
        email: testuser123@hotmail.com
